### ISSUE TITLE
Invalid tag format, ansible-galaxy can't compare role versions

### ISSUE THREAD

**Issue by stdevel** [mondoohq/ansible-mondoo#24]
**Describe the bug**
The latest version of the Ansible role has a different format (v2.0.0) than previous ones (1.5.0) - therefore `ansible-galaxy` during role installation.

**To Reproduce**

Run the `ansible-galaxy install mondoo.client` command.

**Expected behavior**
The tag should have the same format so that `ansible-galaxy` can compare versions.

**Screenshots or CLI Output**
```console
[WARNING]: - mondoo.client was NOT installed successfully: Unable to compare role versions (1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, v2.0.0) to determine the most recent version due to
incompatible version formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role version to install.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Desktop (please complete the following information):**

- OS: Fedora
- OS Version: 37
- Ansible version: 2.14.1
- Ansible role version: 2.0.0

**Additional context**
As a workaround, you can create a file `requirements.yml` with the following content:

```yaml
---
- roles:
  - name: mondoo.client
    version: v2.0.0
```

Afterwards, you can install the specific version like this:

```console
$ ansible-galaxy role install -r requirements.yml
```

Anyhow, this issue should be fixed.

**Comment by benr** [comment]
Indeed, prefixing the version with 'v' broke installation.  Example installation:

```
$ ansible-galaxy install mondoo.client -f
Starting galaxy role install process
- changing role mondoo.client from 1.5.0 to unspecified
- downloading role 'client', owned by mondoo
[WARNING]: - mondoo.client was NOT installed successfully: Unable to compare role versions (1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, v2.0.0, 2.0.1) to determine the most recent version due to incompatible version
formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role version to install.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

Removing the Git tag and release for 'v2.0.0' and then publishing '2.0.1' followed by a push of the 'Release Role' action cleaned up the version history:  https://galaxy.ansible.com/mondoo/client

Installation after fix:

```
$ ansible-galaxy install mondoo.client -f
Starting galaxy role install process
- downloading role 'client', owned by mondoo
- downloading role from https://github.com/mondoohq/ansible-mondoo/archive/2.0.1.tar.gz
- extracting mondoo.client to /home/benr/.ansible/roles/mondoo.client
- mondoo.client (2.0.1) was installed successfully
```
