### ISSUE TITLE
Checking for non-existing mondoo.service

### ISSUE THREAD

**Issue by stdevel** [mondoohq/ansible-mondoo#27]
**Describe the bug**
When 

**To Reproduce**

Install Mondoo using the official [`mondoo.client`](https://galaxy.ansible.com/mondoo/client) Ansible role, e.g. using the following playbook:

```yaml
---
- hosts: linux_hosts
  become: true
  roles:
    - role: mondoo.client
```

**Expected behavior**
Mondoo client is installed.

**Screenshots or CLI Output**
Installation crashes with the following error:

```
TASK [mondoo.client : Ensure deprecated mondoo service is removed] *************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service mondoo.service: host"}
```

**Desktop (please complete the following information):**

I've tested against the following distros:

- AlmaLinux 8
- Ubuntu 22.04
- Fedora 37
- Debian 11

**Additional context**
I think the error exists in the following two files:
- https://github.com/mondoohq/ansible-mondoo/blob/e6e3f89323d3fdee02ec6527d3bcdd7017c0847e/tasks/linux_login.yml (beginning in line 53)
- https://github.com/mondoohq/ansible-mondoo/blob/a86b1c1fd566701741a1f8b755f33d12b6775a19/tasks/linux.yml (beginning in line 66)

Checking against non-existing services fail in Ansible. You'd need to further check the error message, e.g. use `register` and a customized `failed_when` definition.

The Testinfra test still refers to the old service name: https://github.com/mondoohq/ansible-mondoo/blob/a86b1c1fd566701741a1f8b755f33d12b6775a19/molecule/default/tests/test_default.py#L14

**Comment by atomic111** [comment]
@stdevel thanks for bringing it up

**Comment by atomic111** [comment]
@stdevel we fixed it.
