### ISSUE TITLE
Set annotation during installation

### ISSUE THREAD

**Issue by danielwillshare** [mondoohq/ansible-mondoo#33]
**Is your feature request related to a problem? Please describe.**
It would be really nice to be able to submit an annotation directly while initial registration as an optional parameter. If you use annotations for managing the system owner, it will really helpful to get an overview inside the console (if searching for annotations will work soon).

**Describe the solution you'd like**
A string variable which will be used as string for the --annotation parameter while registering the client. If the string contains a "=", the the part before will be the key, the part behind the value. If no "=" is given, the annotation key should be "custom" and the value the whole string.

**Describe alternatives you've considered**
No alternatives ;)

**Additional context**
I think many people could need this, if they have a lot of systems with different owners, so you can create reports based on the annotations an address only the system owner relevant systems. If the annotation will be setup directly in the installation process, it will save a lot of time compared to change this by every single host inside the console.

**Comment by vjeffrey** [comment]
hi @danielwillshare -- did you know you can set annotations on the cli at the scan level?

in other words, i just ran this on my machine:
`cnspec scan local --annotation test=testval --config myconfig`

and when i look at the asset in my space, i see:
<img width="610" alt="Screenshot 2023-09-06 at 08 16 20" src="https://github.com/mondoohq/ansible-mondoo/assets/10341541/74998d96-ca21-498e-8a0d-9989b0688c1f">


i can also search for that asset via annotation in the console, the annotation key should show up in the list if you put your cursor in the searcher:
<img width="536" alt="Screenshot 2023-09-06 at 08 18 31" src="https://github.com/mondoohq/ansible-mondoo/assets/10341541/be133fa6-13f4-4bb5-b9c4-31c55828fb8f">
<img width="328" alt="Screenshot 2023-09-06 at 08 18 40" src="https://github.com/mondoohq/ansible-mondoo/assets/10341541/a9d0e72a-2d54-4ac3-8359-5b51bf8e2cf7">
<img width="1198" alt="Screenshot 2023-09-06 at 08 18 48" src="https://github.com/mondoohq/ansible-mondoo/assets/10341541/504f97ea-8a2c-4a24-805d-57b66b441c98">


does this satisfy your requirement? or is there something else you're looking for?

**Comment by vjeffrey** [comment]
oh -- i forgot to mention, the same is applicable if you use an inventory file, annotations can be added to the asset in that file - let me know if you'd like an example

**Comment by vjeffrey** [comment]
and if you want a simply key, without value, you can run
`cnspec scan local --annotation testjustakey='' --config my-config`
while not ideal, this will work and allow you to search in the console as well. we can improve the syntax in v9

**Comment by vjeffrey** [comment]
oh, im sorry, it appears i misunderstood - and you'd like to have it on the ansible role? ill look into this possibility

**Comment by danielwillshare** [comment]
Thank you. This would be very helpful, because tagging while deploying a huge number of systems will be more simple than go to that systems inside console and tag them one by one or writing an additional role just for tagging systems after installation.

**Comment by kmf** [comment]
@vjeffrey would love this feature!

**Comment by kmf** [comment]
> oh -- i forgot to mention, the same is applicable if you use an inventory file, annotations can be added to the asset in that file - let me know if you'd like an example

Would like to see that @vjeffrey

**Comment by danielwillshare** [comment]
Many thanks for updating, sounds great, but the change isn't currently integrated in galaxy beneath https://galaxy.ansible.com/ui/standalone/roles/mondoo/client/ and https://galaxy.ansible.com/ui/standalone/roles/mondoohq/client/

There's still the version 2.10 without that annotations update. When will this be up to date?

**Comment by vjeffrey** [comment]
hi @danielwillshare , sorry for the delay, we re-introduced the missing annotations passthru in cnspec last week and hope to update the ansible role this week
