### ISSUE TITLE
Update via playbook

### ISSUE THREAD

**Issue by imilchev** [mondoohq/ansible-mondoo#50]
Allow updating clients with cnspec already installed. For example, running the playbook on a machine that already has cnspec v8, it should check if that's the latest version and if it's not, it should perform an update

**Comment by chris-rock** [comment]
This is actually not a problem in the ansible playbook. The mondoo meta package does not have a strict version dependency on cnspec https://github.com/mondoohq/installer/issues/388

**Comment by chris-rock** [comment]
We closed that issue by fixing the package dependencies https://github.com/mondoohq/installer/pull/389
